/*
 * This file is generated by jOOQ.
 */
package com.example.otus.database;


import com.example.otus.database.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Otus extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>otus</code>
     */
    public static final Otus OTUS = new Otus();

    /**
     * The table <code>otus.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Otus() {
        super("otus", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            User.USER
        );
    }
}
