/*
 * This file is generated by jOOQ.
 */
package com.example.otus.database;


import com.example.otus.database.tables.User;


/**
 * Convenience access to all tables in otus.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>otus.user</code>.
     */
    public static final User USER = User.USER;
}
