spring:
  datasource:
    url: jdbc:mysql://10.98.56.125:3306/otus
    username: postgres
    password: postgres
  mvc:
    static-path-pattern: /public/**

#logging:
#  level:
#    org:
#      jooq: DEBUG
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE